ministryofjustice/hmpps-delius-network-terraform

.gitignore
README.md
env_configs/delius-core-dev.properties.sh
inspec_profiles/aws-inspec-profile/README.md
inspec_profiles/aws-inspec-profile/controls/environment.rb
inspec_profiles/aws-inspec-profile/files/terraform.json
inspec_profiles/aws-inspec-profile/inspec.lock
inspec_profiles/aws-inspec-profile/inspec.yml
scripts/aws-get-temp-creds.sh
scripts/generate-terraform-outputs.sh
vpc/peering.tf

Closes #2 
Added tests for Shared VPC vac components

Inspec testing with tags now in places

---

env_configs/delius-core-dev.tfvars
env_configs/delius-core-playpit.tfvars
env_configs/delius-core-sandpit.tfvars
shared-monitoring/main.tf
shared-monitoring/variables.tf
vpc/outputs-zones.tf
vpc/zones.tf

Renamed dns to zones, updated output and consumers

---

vpc/outputs-zones.tf
vpc/zones.tf

Added public domain as an output

---

.gitignore
env_configs/common.tfvars
env_configs/delius-core-dev.properties
security-groups/alfresco-outputs.tf
security-groups/alfresco.tf
security-groups/variables.tf
terraform.tfvars

Added Alfresco Sgs

---

env_configs/common.tfvars
security-groups/spg.tf
security-groups/variables.tf

Added SPG security groups

---

shared-monitoring/terraform.tfvars

Added BCL IPS

---

security-groups/mis-outputs.tf
security-groups/mis.tf
security-groups/variables.tf

Added MIS sgs

---

security-groups/alfresco-outputs.tf
security-groups/alfresco.tf

Added Alfresco elasticache sg

---

security-groups/iaps-outputs.tf
security-groups/iaps.tf
security-groups/variables.tf

Added IAPS sgs

---

apply_playpit_sandpit_dev__shared_vpc_pipeline.Jenkinsfile
plan__playpit_sandpit_dev.Jenkinsfile

'delius-po-test1',
'delius-po-test2',
'delius-training',
'delius-training-test'

Added the four new envs to the Jenkins job

---

apply_playpit_sandpit_dev__shared_vpc_pipeline.Jenkinsfile

adding delius-mis-test env to jenkins file

---

security-groups/mis-outputs.tf
security-groups/mis.tf

created mis test jump host security group

---

es-migration-clusters/main.tf
es-migration-clusters/modules/elasticsearch-cluster/user_data/es_node_user_data.sh
es-migration-clusters/output.tf

Removed es5 cluster as we can do rolling upgrades or a remote re-index to migrate the data

removed es5 cluster as it is not needed

---

persistent-eip/spg-elastic-ip.tf

adding extra tag do not delete on persitant eips

---

security-groups/alfresco-outputs.tf
security-groups/alfresco.tf

Added EFS sg

---

security-groups/alfresco-outputs.tf
security-groups/alfresco.tf

Added elasticsearch sg

---

shared-monitoring/main.tf
shared-monitoring/variables.tf

Added jvm options var

---

testing/chaosmonkey/README.md
testing/chaosmonkey/batch.tf
testing/chaosmonkey/chaosmonkey_job.tf
testing/chaosmonkey/iam.tf
testing/chaosmonkey/main.tf
testing/chaosmonkey/templates/batch_jobs/chaosmonkey.tpl
testing/chaosmonkey/templates/iam_policies/batch_assume_policy.tpl
testing/chaosmonkey/templates/iam_policies/ecs_assume_policy.tpl
testing/chaosmonkey/templates/iam_policies/job_role_policy.tpl
testing/chaosmonkey/terraform.tfvars
testing/chaosmonkey/variables.tf

Self contained terraform coverage for AWS Batch infrastructure.

Managed AWS Batch infrastructure for running Jenkins triggered chaosmonkey testing

---

ses/main.tf
ses/terraform.tfvars
ses/variables.tf
smtp-server/main.tf
smtp-server/policies/ec2.json
smtp-server/smtp_creds.tf
smtp-server/terraform.tfvars
smtp-server/user_data/bootstrap.sh
smtp-server/variables.tf

adding smpt server and ses

---

run.sh
security-groups/shared_monitoring.tf
shared-monitoring/README.md
shared-monitoring/efs.tf
shared-monitoring/elasticsearch_ecs.tf
shared-monitoring/iam.tf
shared-monitoring/kibana.tf
shared-monitoring/kms.tf
shared-monitoring/logstash_ecs.tf
shared-monitoring/main.tf
shared-monitoring/output.tf
shared-monitoring/policies/ecs_role_policy.json
shared-monitoring/policies/es_internal_policy.json
shared-monitoring/policies/kms-policy.json
shared-monitoring/policies/s3_alb_policy.json
shared-monitoring/route53.tf
shared-monitoring/s3bucket.tf
shared-monitoring/sg_rules.tf
shared-monitoring/task_definitions/elasticsearch.conf
shared-monitoring/task_definitions/kibana.conf
shared-monitoring/task_definitions/logstash.conf
shared-monitoring/terraform.tfvars
shared-monitoring/userdata/elasticsearch.sh
shared-monitoring/userdata/monitoring.sh
shared-monitoring/variables.tf

Issue 109 update shared monitoring to ecs 2

---

shared-monitoring/README.md
shared-monitoring/elasticsearch_ecs.tf
shared-monitoring/kibana.tf
shared-monitoring/output.tf
shared-monitoring/variables.tf

Fixed ecs_service_target_grp_deps_shared_mon

---

shared-monitoring/README.md

mis test rebuilt

---

security-groups/mis-outputs.tf
security-groups/mis.tf

adding http-fs related sg groups

---

shared-monitoring/output.tf
shared-monitoring/s3bucket.tf

Added lifecycle rules to shared monitoring bucket

---

shared-monitoring/iam.tf
shared-monitoring/variables.tf

Fixed shared monitoring

---

shared-monitoring/elasticsearch_ecs.tf
shared-monitoring/userdata/elasticsearch.sh
shared-monitoring/userdata/monitoring.sh
shared-monitoring/variables.tf

Updates for changing ES instance types

---

peering-connection/main.tf
peering-connection/peering-bastion.tf
peering-connection/variables.tf
security-groups/ssh-bastion-in.tf

Issue156 dam 333 update db sg

---

smtp-server/main.tf

Add smtp ingress rule from IAPS SG

---

es-migration-clusters/terraform.tfvars
vpc/outputs-zones.tf
vpc/zones.tf

Dam 394 psn testing

---

smtp-server/main.tf
smtp-server/user_data/bootstrap.sh

adding log group for smtp

---

security-groups/delius-core_mis.tf

Removed some unnessary rules.
Closes #174 #173

Added new rule for egress on 4903 to OEM.

---

vpc/main.tf
vpc/variables.tf
vpc/zones.tf

Also switches strategic acct from (mistakenly) being created as a private zone to being a public zone

Adds prod acct provider and r53 strategic zone delegation records

---

vpc/outputs-zones.tf
vpc/zones.tf

This pull request ensures the terraform doesn't attempt to create certificates or validation records for the strategic zone in Production, as the strategic zone isn't managed by Terraform. It also ensures the `strategic_public_zone_id` output is a string, rather than a list containing a single element, so that the type is consistent between all environments.
```
[terragrunt] [/home/tools/data/vpc] 2019/12/05 14:26:58 Running command: terraform --version
[terragrunt] 2019/12/05 14:26:59 Reading Terragrunt config file at /home/tools/data/vpc/terraform.tfvars
[terragrunt] 2019/12/05 14:26:59 Assuming IAM role arn:aws:iam::050243167760:role/terraform
[terragrunt] 2019/12/05 14:27:04 Running command: terraform plan -var-file=/home/tools/data/env_configs/common-prod/common.tfvars …
```

Update strategic_public_zone_id output to be a string and disabled some resources in prod

---

ecs-cluster/templates/ec2/ecs-host-userdata.tpl
ecs-cluster/variables.tf

Example of AWS OpenTelemetry / ServiceMap in the `delius-core-dev` environment:

ALS-2724 Add OpenTelemetry agent to support X-Ray metric collection

---

smtp-server/main.tf
terragrunt.hcl
vpc/main.tf
vpc/zones.tf

Upgrade guide: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade

Upgraded AWS provider to v3
